name: Jordan Kobellarz
description: Web Developer

markdown: kramdown
highlighter: rouge
paginate: 15
baseurl: /
domain_name: 'http://jordankobellarz.github.com'
google_analytics: 'UA-58555211-1'

# Details for the RSS feed generator
url: 'http://jordankobellarz.github.com'

author:
    name: Jordan Kobellarz
    thumb: /assets/images/profile.jpg
    bio: Web Developer e estudante de Sistemas de Informação. De vez enquando durmo um pouco.
    url:
        site: 'http://jordank.me'
        facebook: 'https://www.facebook.com/jordan.kobellarz'
        twitter: 'https://twitter.com/jordankobellarz'
        linkedin: 'http://br.linkedin.com/in/jordankobellarz'
        email: 'jordan.kobellarz@gmail.com'

urls:
    about: /sobre

img_path: /assets/images/
